### ISSUE TITLE
Sometimes the dock failed to load an application's icon and so the application can't be pinned either

### ISSUE THREAD

**Issue by dangvd** [dangvd/crystal-dock#21]
This happens if the app is found on the Application List, but [QIcon::fromTheme](https://doc.qt.io/qt-6/qicon.html#fromTheme) returns a null icon. This also causes the app to be unable to get Pinned on the dock.

We need to find a better way to load the icon.

**Comment by dangvd** [comment]
Now I can't reproduce this anymore on my system (OpenSUSE Tumbleweed) after a recent update. It seems some people on Arch-based distros are still having this issue though.

**Comment by dwconsulting** [comment]
I'm still experiencing it on Fedora latest under Plasma.
![image](https://github.com/user-attachments/assets/4868a5a6-db89-4a74-8572-eb758b63a3c6)

**Comment by dwconsulting** [comment]
> I'm still experiencing it on Fedora latest under Plasma. ![image](https://private-user-images.githubusercontent.com/8230739/369118814-4868a5a6-db89-4a74-8572-eb758b63a3c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Njk3ODksIm5iZiI6MTcyNjc2OTQ4OSwicGF0aCI6Ii84MjMwNzM5LzM2OTExODgxNC00ODY4YTVhNi1kYjg5LTRhNzQtODU3Mi1lYjc1OGI2M2EzYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTgxMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRhZmEwYTQyYzZkMGE0NGZlM2E5OTQ3NzdmMTgxNjU1YmY5ZjA2ZGVlYjIyMzE0MTBjOGNmZDEyODE2M2IwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZySphJ5MMKDlRq5UhNEoQpM8MDzlhwIpcFRQpFnh_Xk)

I should add, crystal-dock 2.4 Alpha.

**Comment by dangvd** [comment]
Ah thanks, I just installed VS Code and I can reproduce it.

**Comment by dangvd** [comment]
Umm no, restarting the dock fixed it.

How did you install VS Code btw? Did you use the RPM from the official website?

**Comment by dwconsulting** [comment]
I tried restarting, didn't help me.

Regarding VSCode, I followed Microsoft's instructions and added the repo.

https://code.visualstudio.com/docs/setup/linux

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Thanks well I'll try to see what other applications I can try to install to reproduce this.

**Comment by dwconsulting** [comment]
Is there anything I can do with compiling or command line switches to
gather debug info for you?

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Thanks, so the issue is loading icons -- QIcon::fromTheme() basically looks at the current theme's location and fallback locations according to [freedesktop.org](http://freedesktop.org/) standard.

This bug happens when somehow the icon is not stored in those standard locations (or less likely, a bug in Qt/KDE icon loading code).

If you could, could you please locate where is the icon for VS Code stored in your system? The filename should be vscode.png and it's probably stored in some sub-dir inside /usr/share/

**Comment by dwconsulting** [comment]
Mine are stored in ~/.icons/[icon pack name]

e.g.: ~/.icons/Reversal/apps/scalable/vscode.svg and
***@***.***/scalable/vscode.svg




"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Thanks, that looks ok to me, not sure why it was not loaded :/

**Comment by dangvd** [comment]
Thanks for the update.
It seems that it is a different bug then: #56 
I'll put more debug info into the binary to help with these cases.

**Comment by dangvd** [comment]
Also I just released a new version which will print out some error messages to help debugging it:
https://github.com/dangvd/crystal-dock/releases/tag/v2.5

**Comment by 2handband** [comment]
Having this problem consistently with Transcribe! on Arch Linux, installed from the AUR. It's an unusual package as the vendor only provides an install.sh file, from which an PKGbuild was created for Arch Linux installation. All other applications seem to be functioning correctly. I have just updated to 2.5, and the issue persists. Any information I can provide, please specify.

**Comment by 2handband** [comment]
https://github.com/archlinux ~]$ crystal-dock
QSocketNotifier: Can only be used with threads started with QThread
Could not find application with id: Transcribe!. The window icon will have limited functionalities.

**Comment by 2handband** [comment]
@dangvd : built the latest version. Regret to inform you that I still do not have an icon for transcribe.

**Comment by dwconsulting** [comment]
If I change the fixedAppId for Transcribe to equal
"com.seventhstring.transcribe" and recompile/install on my Fedora KDE box
it works. (in application_menu_config.cc)


"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by 2handband** [comment]
Okay... I didn't modify anything, I just compiled. Could I get a little more 
detail on what I have to change and where I find it?

**Comment by dwconsulting** [comment]
In the /src/model folder, there's a file called application_menu_config.cc

In that file, around line 230-250 should be a block that starts with "//
Special fix for Transcribe!"

Two lines after that is a line that starts with "fixedAppId = ". The value
in the string to the right should be "com.seventhstring.transcribe".  Save,
recompile/install and relaunch.

Make sure you've closed the dock before recompiling/reinstalling just to be
safe.

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Let's move the discussion to #56 because that's the actual bug.
I'll close this one for now because so far we've only really seen #56 and not this.

**Comment by dangvd** [comment]
Re-opening.

From @dwconsulting 
Could not find icon with name: code-insiders in the current icon theme and
its fallbacks. The window icon will have limited functionalities.

@dwconsulting : so in this case, even though this is not in the Breeze theme, it should have been in the fall-back search path (as determined by Qt/KDE). I'm not sure why it was not.

**Comment by dwconsulting** [comment]
That is my thought as well... if Plasma can find the icon QT should be able
to as well, right?

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
OK so I am having this issue as well with Firefox (Snap) on Kubuntu 24.10:

Could not find icon with name: /snap/firefox/5134/default256.png in the current icon theme and its fallbacks. The window icon will have limited functionalities.

**Comment by dangvd** [comment]
Latest fix released in v2.7

Will keep this open for further fixes

**Comment by celtic34fr** [comment]
I'm just install v 2.7 on Ubuntu 24.10 use on Plasma 6.15
For some application like WhatSie (Qt WhatsApp Web Client - snap installation), icon in dock isn't the same in menu and cannot be pinned ???
First, Is it possible to add application in 'Edit launchers' as 'Add System Command'  by picking then in list of application installed ?
Second, in 'Visibility' with 'auto-hide' option actived the dock is hidden when a windows is activ whatever the size of the latter, whether the window covers it or not, even on a second screen or the dock is absent. Have you any solution to resolve this problem ?

**Comment by dangvd** [comment]
@celtic34fr  Hi, could you please create one bug for each request/bug? it would make it much easier to track them that way. Thanks!

**Comment by dangvd** [comment]
Let's close this one for now and open a new one with more specific info when it happens again.
