### ISSUE TITLE
Sometimes the dock failed to match a window to an application and so it can't be pinned

### ISSUE THREAD

**Issue by dangvd** [dangvd/crystal-dock#56]
Sometimes the app_id returned by the window manager does not match that in the application list.
Crystal Dock already tries some heuristics to help with matching but there might be more corner cases:
https://github.com/dangvd/crystal-dock/blob/a911f28371a2be247185e5ffdc458d41ca274757/src/display/window_system.cc#L482

**Comment by dwconsulting** [comment]
Debug info from 2.5 release. I know the first two aren't directly related as they don't show up in the dock, but did not know if they would help diagnose the issue or point in the right direction.

Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
Could not find application with id: org.kde.plasmashell. The window icon will have limited functionalities.
Could not find application with id: Code - Insiders. The window icon will have limited functionalities.
Could not find application with id: net.code-industry.masterpdfeditor5. The window icon will have limited functionalities.

**Comment by dwconsulting** [comment]
(adding screenshot of KDE Menu Editor entry for VS Code Insider)
![image](https://github.com/user-attachments/assets/1f142dc3-8307-4cc0-b46b-948702a7a5b2)
I do notice that the debug message from crystal-dock is mixed-case "Code - Insiders", where the menu item is "Visual Studio Code - Insiders".

Also, the window title and tooltip in the dock both include the "Visual Studio ". Would something in the dock code be truncating the left of the string?

**Comment by dangvd** [comment]
Thanks a lot!

So, in the application list, the app_id for VS Code is the basename of the .desktop file. In my case, it's "code" (from /usr/share/applications/code.desktop)
Could you please check what's yours?

We'll need to make sure we can match it with the app_id from the window (Code - Insiders) somehow.

**Comment by dwconsulting** [comment]
/usr/share/applications🔒
❯ ls | grep code
code-insiders.desktop
code-insiders-url-handler.desktop

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Great, thanks!

So we'll need to add another hack to match "code-insiders" with "Code - Insiders". I'll add it to the next version.

**Comment by dwconsulting** [comment]
I wonder if other apps do that too? Perhaps a .toLower and then replace " " to try another match hack?

**Comment by dangvd** [comment]
Yeah the hack I will do is:
- Remove spaces
- Convert to lower cases

**Comment by dangvd** [comment]
Ah we just need to remove spaces because lower case conversion is already there.

**Comment by 2handband** [comment]
@archlinux ~]$ crystal-dock
QSocketNotifier: Can only be used with threads started with QThread
Could not find application with id: Transcribe!. The window icon will have limited functionalities.

**Comment by dangvd** [comment]
@2handband thanks! Could you please check what's the name of the desktop file (.desktop) for Transcribe in the application folders (e.g. /usr/share/applications) ?

**Comment by 2handband** [comment]
> @2handband thanks! Could you please check what's the name of the desktop file (.desktop) for Transcribe in the application folders (e.g. /usr/share/applications) ?

seventhstring-transcribe.desktop

**Comment by dangvd** [comment]
@2handband  Thank you! I'll add a fix for that as well.

**Comment by dangvd** [comment]
@dwconsulting @2handband the fixes have been submitted to the main tree now. If you could compile from source, would you mind trying it to see if it works for you? Thanks.

**Comment by 2handband** [comment]
@dangvd: It's been years since I built anything from source, but I'll try it tomorrow. We'll see if my old skills are still intact!

**Comment by dwconsulting** [comment]
VSCode Insiders is fixed. I went in and tested the following code to add support for DBeaver Enterprise and it works on my system:

<code>
  // Special fix for DBeaver EE
  if (id == "dbeaverenterprise") {
    fixedAppId = "dbeaver-ee";
    if (findApplication(fixedAppId) != nullptr) {
      return fixedAppId;
    }
  }
</code>

**Comment by dwconsulting** [comment]
THANK YOU!!!
![image](https://github.com/user-attachments/assets/0cfacca4-d4a1-459b-aef8-5985dfed825d)

**Comment by dangvd** [comment]
@dwconsulting thank you! I'll add that DBeaver fix as well.
Btw on your screenshots, why are the task indicators too close to (and half covered by) the application icons?

**Comment by dwconsulting** [comment]
Not sure?

[image: image.png]
"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
It should look like in:
https://github.com/dangvd/crystal-dock/wiki/Screenshots

Did you change any of:
- System display global scale
- Crystal Doc's Appearance Settings: min/max icon size, icon spacing factor?

**Comment by dwconsulting** [comment]
I believe I did... it was a while ago if so
![image](https://github.com/user-attachments/assets/4731e856-620d-4bcf-af2a-b0fef2429af3)

**Comment by dangvd** [comment]
Thanks, I've filed a bug for that #63

**Comment by dangvd** [comment]
@dwconsulting @2handband I've updated the code to include dwconsulting's fixes for DBeaver EE and Transcribe!

**Comment by dangvd** [comment]
@dwconsulting : also added your name to https://github.com/dangvd/crystal-dock/wiki/Author-&-Contributors, if you don't mind.

**Comment by dwconsulting** [comment]
Thanks a bunch, just trying to help because it's a nice app.

**Comment by 2handband** [comment]
Still not fixed on my Arch build. I've reinstalled it twice, and rebooted the system just to be sure.

**Comment by dangvd** [comment]
@2handband just wanted to double check: you did:
$ make && sudo make install
and reran:
$ crystal-dock
?

If it's still not working, could you please double check the name of the desktop file (.desktop) for Transcribe in the application folders (e.g. /usr/share/applications) ? There might be several of them (and only one of them is actually for the application).

**Comment by 2handband** [comment]
@dangvd: the file seventhstring-transcribe.desktop is in /usr/shar/applications

Files called seventhstring-transcribe.png are in directories /usr/share/icons/hicolor/_x_/apps

**Comment by dangvd** [comment]
Thanks @2handband 

Then the first fix:

fixedAppId = "seventhstring-transcribe";

should have worked.

I'm not sure why it did not.

**Comment by 2handband** [comment]
@dangvd: I don't either. I have icons in the more traditional app launchers; just not in crystaldock. it shows up in Lost and Found... but it does show up. Not sure what to make of it. Should I change that line to fixedAppId = "seventhstring-transcribe"; and try compiling again?

**Comment by dangvd** [comment]
@2handband yeah could you please change that line to fixedAppId = "seventhstring-transcribe"; and try compiling again?

**Comment by dwconsulting** [comment]
@dangvd Noticed Virtualbox wasn't finding either (fedora), thoughts about this for a fix?

<code>
  // Special fix for Virtualbox
  if (id == "virtualboxvm" || id == "virtualboxmachine" || id == "virtualboxmanager") {
    fixedAppId = "virtualbox";
    if (findApplication(fixedAppId) != nullptr) {
      return fixedAppId;
    }
  }
</code>

**Comment by 2handband** [comment]
@dangvd: Where is the local configuration file for crystaldock located?

**Comment by dangvd** [comment]
@dwconsulting thanks I will put it in. 
@2handband https://github.com/dangvd/crystal-dock/wiki/Documentation#config-location

**Comment by dangvd** [comment]
@dwconsulting  @2handband : I've submitted a change that improves matching and get rid of most of the specific hacks. Could you please try it?

Also @dwconsulting I've submitted a fix for #63 so hopefully it will look better for you.

**Comment by 2handband** [comment]
Just updated and it seems fine... except I still don't have a Transcribe icon. I just looked over the config files; can't see anything there that would be relevant. I wonder why the fixes are working on your machines and not mine.

**Comment by dangvd** [comment]
@2handband could you double check the error message? Is it still the same one?

**Comment by 2handband** [comment]
@dangvd here's the full output:

`QSocketNotifier: Can only be used with threads started with QThread
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
Could not find application with id: Transcribe!. The window icon will have limited functionalities.
Could not find application with id: Transcribe!. The window icon will have limited functionalities.
Could not find application with id: Transcribe!. The window icon will have limited functionalities.
Could not find application with id: Transcribe!. The window icon will have limited functionalities.

`

**Comment by 2handband** [comment]
Here's my question: is there a reasonable/easy way to duplicate KoolDock's functionality? With KoolDock on TDE, I can just click and drag from a traditional app launcher to the KoolDock configuration dialog, and all the appropriate settings are transferred. Literally all I want out of a dock is  spiffy-looking pop-up to launch apps from.

**Comment by 2handband** [comment]
@dangvd that sounds like exactly what I want. It's cool that you're putting all this extra functionality into CrystalDock, because some people will probably find it useful, but if I'm being honest i don't care  about any of it. For me, KoolDock does literally everything I want a dock to do. Anything else is just window dressing.

**Comment by dwconsulting** [comment]
Amazing work, just pulled and built, matching all my problem apps except:

Could not find application with id: VirtualBox Machine. The window icon will have limited functionalities.

**Comment by 2handband** [comment]
@dwconsulting @dangvd I just installed virtualbox to test it on my system. Can confirm it's also not matching on Arch-based builds. At the moment it's just this and Transcribe; everything else works.

**Comment by dangvd** [comment]
@dwconsulting @2handband  thanks for testing it.
It seems we still need some specific fixes then.
Btw would it be possible for you to attach your .desktop files for the virtualbox/transcribe? Just wanted to check if there's some other field there that I need to try matching against.

**Comment by dangvd** [comment]
@2handband also #71 is now implemented on main tree.

**Comment by dangvd** [comment]
I just added the special fix for VirtualBox as @dwconsulting suggested.

**Comment by dwconsulting** [comment]
FYI, it seems that it depends on the icon pack being used also, e.g. Breeze
icon pack did not match DBeaver or Code, but Reversal ones do.


"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
If you see error depending on the icon theme, it should be #21, not this bug.
Could you please double check the error message on the Crystal Dock console for DBeaver/Code on Breeze?

**Comment by dwconsulting** [comment]
Could not find icon with name: code-insiders in the current icon theme and
its fallbacks. The window icon will have limited functionalities.

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dwconsulting** [comment]
[image: image.png]
Only two icons that match "code" in Breeze pack

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
Right, so that's #21, I will re-open that one.

**Comment by 2handband** [comment]
@dangvd: you're on Tumbleweed, is that correct? If so, when you installed transcribe!, did you use the flatpak?

**Comment by dangvd** [comment]
@2handband no, I don't have Transcribe, I rely on you two to test it. About Flatpak I think their website said that you should not use it though: https://www.seventhstring.com/xscribe/download_linux.html

**Comment by dwconsulting** [comment]
Personally I am okay, thank you.

"Since it is so likely that children will meet cruel enemies, let them at
least have heard of brave knights and heroic courage" - C. S. Lewis

**Comment by dangvd** [comment]
@dwconsulting Thanks for confirming.

**Comment by dangvd** [comment]
Recent improvements released in v2.6

Will keep this open for further fixing.

**Comment by dangvd** [comment]
In v2.9: this issue happens again, with for example Google Chrome. The cause is because windowGeometryChanged() event could get triggered before windowAdded() event and the App Id fixing code is in the latter, not the former. Will fix this for v2.10

**Comment by dangvd** [comment]
This is getting very long so let's close this one for now and open a new one with more specific info when it happens again.

**Comment by dangvd** [comment]
Continued in #131
